import ConditionalHeader from "@/components/ConditionalHeader";
import { Footer } from "@/components/Footer";
import { AuthProvider } from "@/providers/authProvider";
import StoreProvider from "@/providers/storeProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          {" "}
          <AuthProvider>
            <ConditionalHeader />
            {children}
            <Footer />
          </AuthProvider>{" "}
        </StoreProvider>
      </body>
    </html>
  );
}
